language: php
sudo: false
php:
  - '8.1'

services:
  - mysql

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console --env=test doctrine:fixtures:load

script:
  - php bin/phpunit